### ISSUE TITLE
Give the possibility to add extra parameters.

### ISSUE THREAD

**Issue by Nemecsek** [chekoduadarsh/YOPO-You-Only-Plot-Once#6]
**Is your feature request related to a problem?**
I am using Histograms, but the number of bins is automatic and cannot be changed.
Other plot types can be optimized by adding extra parameters (i.e. to change the size of scatterplots' markers). 

**Describe the solution you'd like**
Of course it is not possible to add parameters according to every users' needs. 

The easiest solution is to give the possibility to enter extra params into an edit box such as:
![Screenshot_20220218_092905](https://user-images.githubusercontent.com/25978536/154646374-b9eae766-4ccf-47e6-b4e6-24b7b7c0f206.png)

This string can be transformed into a dictionary with `eval(f'dict({  edit_box_content })')`, and the dictionary then  added to the plots' parameters.

**Comment by chekoduadarsh** [comment]
@Nemecsek Thank you for your feed back!!

 This is such a wonderful idea, I will start working on it immediately. I will raise PR in this few days!! 

If you have any suggestion on how to beautify and make this feature easier please let me know.

Thanks a lot for trying this library out!

**Comment by Nemecsek** [comment]
Yesterday I was talking to my boss, and have shown him some data distribution in a minute using your lib. It is very intuitive! Thank YOU for the great job. 

There are ways to improve it, but according to my opinion it is better to wait for more requests from users before beginning to restyle it. I will open further issues about possible improvements.
